version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: rm95749
      MYSQL_PASSWORD: 101202
      MYSQL_DATABASE: QualyMec-FIAP
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/QualyMec-FIAP
      SPRING_DATASOURCE_USERNAME: rm95749
      SPRING_DATASOURCE_PASSWORD: 101202
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80
volumes:
  dbbase:
  